# Generated by Django 2.2.17 on 2021-02-02 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botname', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=255)),
                ('created', models.DateTimeField(db_index=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='messageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('isbot', models.BooleanField(default=False)),
                ('created', models.DateTimeField(db_index=True, editable=False)),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_name', to='HotelChatbot.Bot')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
